#!/bin/bash
name=DTI_raw
#convert nifti to mif
mrconvert -fslgrad $name.bvec $name.bval $name.nii.gz \
        $name.mif -force


# creat a mask
dwi2mask $name.mif - | maskfilter - dilate ${name}_preproc_mask.mif -npass 3

#Denoising
dwidenoise $name.mif ${name}_denoise.mif -noise noiselevel.mif -mask ${name}_preproc_mask.mif

#Gibbs Ring artifact
mrdegibbs ${name}_denoise.mif ${name}_degibbs.mif 

#motion and distortion correction
#dwiextract raw1000.mif b0.mif -bzero

dwifslpreproc ${name}_degibbs.mif ${name}_preproc.mif \
              -rpe_none -pe_dir AP
              
# bias filed correction
dwibiascorrect ants ${name}_preproc.mif ${name}_biascorr.mif

#prepare for alignment to T1
dwiextract ${name}_biascorr.mif -bzero - | mrmath -axis 3 - mean ${name}_b0.nii

#prepare T1
bet T1_3D.nii T1_3D_bet.nii -R

# use ants to registrate
antsRegistrationSyN.sh -d 3 -f ${name}_b0.nii -m T1_3D_bet.nii.gz -t r -o T1_3D_to_dti


# if you need the mat file for mrtransform, execute next code.
#ConvertTransformFile 3 ants0GenericAffine.mat ants0GenericAffine.txt

#tranformconvert ants0GenericAffine.txt itk_import anat2dtialign_mrtrix.txt
#mrtransform -linear anat2dtialign_mrtrix.txt T1_3D.nii T1_3D_to_dti.nii
