#! /bin/bash

patientName=lilin

# create a mask
dwi2mask ${patientName}_dti_biascorr.mif - | maskfilter - dilate ${patientName}_dti_biascorr_mask.mif -npass 3

# create diffusion tensor
dwi2tensor -mask ${patientName}_dti_biascorr_mask.mif ${patientName}_dti_biascorr.mif ${patientName}_dt.mif 

# calculate eigevectors
tensor2metric ${patientName}_dt.mif -fa ${patientName}_dt_fa.mif -ad ${patientName}_dt_ad.mif \
                                    -adc ${patientName}_dt_md.mif -rd ${patientName}_dt_rd.mif 

# constrained spherical deconvolution (CSD)
# estimate response function for wm, gm, csf
dwi2response dhollander ${patientName}_dti_biascorr.mif ${patientName}_wm.txt ${patientName}_gm.txt ${patientName}_csf.txt \
             -voxels ${patientName}_ms5tt_voxels.mif
             
# estimate fiber orientation distribution FOD
dwi2fod msmt_csd ${patientName}_dti_biascorr.mif  \
        ${patientName}_wm.txt ${patientName}_dti_wmCsd.mif \
        ${patientName}_gm.txt ${patientName}_dti_gmCsd.mif \
        ${patientName}_csf.txt ${patientName}_dti_csfCsd.mif


## For next part, you should choose or modify code based on your own study!!

# create ROIs
mrthreshold -abs 0.2 ${patientName}_dt_fa.mif - | mrcalc - ${patientName}_dti_biascorr_mask.mif -mult ${patientName}_dti_wmMask.mif

# put your ROIs in folder ROIs
# extract ROIs from freesurfer
mri_extract_label -dilate 2 aparc.a2009s+aseg.nii.gz 10 ROIs/${patientName}_lh_thalamus.nii.gz
mri_extract_label -dilate 2 aparc.a2009s+aseg.nii.gz 11111 ROIs/${patientName}_lh_cuneus.nii.gz

# all tractography results are saved in folder trks
mkdir trks
# whole brain tractography
tckgen -algo iFOD2 -act ${patientName}_5ttseg.mif -backtrack -crop_at_gmwmi \
       -cutoff 0.05 -angle 45 -minlength 20 -maxlength 200 \
       -seed_image ${patientName}_dti_wmMask.mif -select 200k \
       ${patientName}_dti_wmCsd.mif \
       trks/${patientName}_fibs_200k_angle45_maxlen200_act.tck

# Roi based tractography, using roi from freesurfer
tckgen -algo iFOD2 -cutoff 0.05 -angle 45 \
       -minlength 20 -maxlength 100 \
       -seed_image ROIs/${patientName}_lh_thalamus.nii.gz \
       -include ROIs/${patientName}_lh_cuneus.nii.gz \
       -seed_unidirectional \
       -stop \
       ${patientName}_dti_wmCsd.mif \
       trks/${patientName}_fibs_OR.tck
       
# ROI based tractography, left mPFC to Superiro Colliculusto
tckgen -algo iFOD2 -cutoff 0.05 -angle 45 \
       -minlength 20 -maxlength 100 \
       -seed_image ROIs/ROI_L_mPFC2_to_${patientName}.nii.gz \
       -include ROIs/ROI_L_SuperiroColliculus_to_${patientName}.nii.gz \
       -seed_unidirectional \
       -stop \
       ${patientName}_dti_wmCsd.mif \
       trks/${patientName}_fibs_left_mPFC_to_left_SC.tck

# ROI based tractography, left FEF to Superiro Colliculusto
tckgen -algo iFOD2 -cutoff 0.05 -angle 45 \
       -minlength 20 -maxlength 100 \
       -seed_image ROIs/ROI_L_FEF_to_${patientName}.nii.gz \
       -include ROIs/ROI_L_SuperiroColliculus_to_${patientName}.nii.gz \
       -seed_unidirectional \
       -stop \
       ${patientName}_dti_wmCsd.mif \
       trks/${patientName}_fibs_left_FEF_to_left_SC.tck
