#!/bin/bash
# "fMRI" for fMRI folders
# "T1" for structual folder

# Process fMRI folders
folders=$(ls |grep "fMRI*")
for folder in $folders
do
	echo "In folder: $folder"
	cd $folder
	let i=i+1
	prefixName="epi_r$i"

	uniq_images IM*[0123456789] > uniq_image_list.txt
	Dimon -infile_list uniq_image_list.txt \
		-gert_create_dataset	\
		-gert_write_as_nifti	\
		-gert_to3d_prefix $prefixName	\
		-gert_outdir ..		\
		-dicom_org		\
		-use_last_elem		\
		-save_details Dimon.details	\
		-gert_quit_on_err  
	\rm uniq_image_list.txt
	cd ..
done

# Process T1 folder
echo "In folder: T1"
cd T1
uniq_images IM*[0123456789] > uniq_image_list.txt
Dimon -infile_list uniq_image_list.txt \
	-gert_create_dataset	\
	-gert_write_as_nifti	\
	-gert_to3d_prefix T1_3D	\
	-gert_outdir ..		\
	-dicom_org		\
	-use_last_elem		\
	-save_details Dimon.details	\
	-gert_quit_on_err  
\rm uniq_image_list.txt