#!/bin/tcsh -xef


set mask_dset = /media/win/MRI_Project/fMRI2021/strabismus_all_6s/mask_group+tlrc

set dirA = /media/win/MRI_Project/fMRI2021/strabismus_all_6s

set results_dir = patient.result2
if ( ! -d $results_dir ) mkdir $results_dir

3dttest++ -prefix $results_dir/ttest -AminusB -paired \
	  -resid q+tlrc 		\
	  -ACF 		\
	  -mask $mask_dset				\
	  -setA Convergence				\
	  	NCC "$dirA/stats.NCC+tlrc[1]"		\
	  	SH "$dirA/stats.SH+tlrc[1]"		\
		WM "$dirA/stats.WM+tlrc[1]"			\
		GTT "$dirA/stats.GTT+tlrc[1]"			\
		QL "$dirA/stats.QL+tlrc[1]"			\
		ZJ "$dirA/stats.ZJ+tlrc[1]"			\
		FRR "$dirA/stats.FRR+tlrc[1]"			\
		WJH "$dirA/stats.WJH+tlrc[1]"			\
		ZH "$dirA/stats.ZH+tlrc[1]"	\
	  -setB Relax					\
		NCC "$dirA/stats.NCC+tlrc[4]"		\
	  	SH "$dirA/stats.SH+tlrc[4]"		\
		WM "$dirA/stats.WM+tlrc[4]"			\
		GTT "$dirA/stats.GTT+tlrc[4]"		\
		QL "$dirA/stats.QL+tlrc[4]"			\
		ZJ "$dirA/stats.ZJ+tlrc[4]"			\
		FRR "$dirA/stats.FRR+tlrc[4]"			\
		WJH "$dirA/stats.WJH+tlrc[4]"			\
		ZH "$dirA/stats.ZH+tlrc[4]"				

## 计算FWE的体素阈值，结果输出到clustsim.txt
mv q* $results_dir
# get three parameters in ACF file
set para1 = `cat $results_dir/q.ACFparam.txt | awk '{split($0,a); print a[1]}'`
set para2 = `cat $results_dir/q.ACFparam.txt | awk '{split($0,a); print a[2]}'`
set para3 = `cat $results_dir/q.ACFparam.txt | awk '{split($0,a); print a[3]}'`
echo "ACF values are: $para1, $para2, $para3"

# calculate FWE
3dClustSim -mask $mask_dset -acf $para1 $para2 $para3 > "$results_dir/clustsim.txt"

echo "Finished"