#!/usr/bin/env tcsh


set subj = LuoSha
set gname = Normal
set top_dir = /home/rogerlin/fMRI/PA4LuoSha/

afni_proc.py -subj_id ${subj}						\
	-script proc.${subj} -scr_overwrite				\
	-blocks tshift align tlrc volreg blur mask scale regress	\
	-copy_anat T1_3D.nii				\
	-dsets							\
		epi_r1.nii				\
		epi_r2.nii				\
	-radial_correlate_blocks tcat volreg				\
	-tcat_remove_first_trs 5					\
	-tshift_opts_ts -tpattern altplus				\
	-tshift_interp -quintic						\
	-align_opts_aea -check_flip					\
	-tlrc_base MNI_avg152T1+tlrc					\
	-volreg_align_to MIN_OUTLIER					\
	-volreg_align_e2a						\
	-volreg_tlrc_warp						\
	-blur_size 4.0							\
	-regress_stim_times						\
		${top_dir}/stimuli/Convergence.txt						\
		${top_dir}/stimuli/Relax.txt						\
		${top_dir}/stimuli/Rest.txt							\
	-regress_stim_labels 						\
		convergence relax rest				\
	-regress_basis 'BLOCK(6,1)'					\
	-regress_censor_motion 0.3					\
	-regress_motion_per_run						\
	-regress_opts_3dD						\
		-gltsym 'SYM: convergence - relax' -glt_label 1 C-R	\
	-regress_compute_fitts						\
	-regress_make_ideal_sum sum_ideal.1D				\
	-regress_est_blur_epits						\
	-regress_est_blur_errts
		
	

